services:
  nginx:
    image: nginx:alpine
    ports:
      - "${XDBG_EXAMPLE_PORT:-8888}:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build:
      context: ./docker/php
    volumes:
      - .:/var/www/html
    environment:
      PHP_IDE_CONFIG: "serverName=xdbg-demo"
    extra_hosts:
      - "host.docker.internal:host-gateway"
